import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import nextSvg from "../public/next.svg"
import Blogs from './Blogs'
const inter = Inter({ subsets: ['latin'] })

export default function Home({data}: {data:any}) {
  return (
    <>
  <div className={styles.container}>
     <Head>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>

     <p>
       <div className='bg-black  py-2 flex justify-center text-white text-bold text-2xl'>Rick and Morty</div>
      <Blogs />
     </p>
   </div>
    </>
  )
}
export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();
 
  return {
    props: { data },
  };
 };